#!/bin/sh
set -e

# Define the destination config path in a writable directory
DEST_CONF="/data/redis.conf"

# Check if the secret file exists
if [ ! -f /run/secrets/redis_password ]; then
  echo "ERROR: Redis password secret not found at /run/secrets/redis_password"
  exit 1
fi

# Read the password from the secret file
REDIS_PASSWORD=$(cat /run/secrets/redis_password)

# Generate the redis.conf file from scratch
cat > "$DEST_CONF" <<EOF
# Generated by entrypoint.sh
bind 0.0.0.0
requirepass $REDIS_PASSWORD
appendonly yes
dir /data
EOF

# Execute the original Redis entrypoint with the new config file
exec docker-entrypoint.sh redis-server "$DEST_CONF"
